---
- hosts: '{{ var_hosts | default("laputa.danizen.net") }}'
  become: true
  vars:
    minecraft_plugin_dir: '/srv/minecraft/plugins'

  pre_tasks:
    - name: Add the epel-release on CentOS
      when: "ansible_os_family == 'RedHat'"
      yum:
        name: epel-release
        state: latest

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

    - role: devops-coop.minecraft
      minecraft_url: https://pypi.danizen.net/minecraft
      minecraft_version: 1.12.2
      minecraft_ops:
        - danizen
      minecraft_whitelist:
        - danizen
        - ScorpionBuild
        - PlacHerobrine
      minecraft_server: spigot
      minecraft_server_properties:
        'level-seed': -4829013407982591683
      minecraft_hook_before_start: '{{ playbook_dir }}/download-plugins.yml'

