---
- hosts: localhost
  connection: local
  become: true

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

    - role: devops-coop.minecraft
      minecraft_version: 1.12.1
      minecraft_ops:
        - danizen
      minecraft_whitelist:
        - danizen
      minecraft_server: spigot
